# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Marco' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Marco

  pod ‘Firebase/Auth'
  pod 'Firebase/Analytics'
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'

  target 'MarcoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MarcoUITests' do
    # Pods for testing
  end

end
